### ISSUE TITLE
imu原始数据

### ISSUE THREAD

**Issue by lijh1024** [HR-zju/ZJU-Radar-Dataset#2]
你好，请问可以公布imu原始数据吗，现在的这个topic: /imu/data 只包含了orientation信息，没有angular_velocity和linear_acceleration信息
orientation: 
  x: -0.008809879422187805
  y: -0.0014910817844793203
  z: -0.9972180724143983
  w: -0.074002206325531
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
angular_velocity_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 0.0
  y: 0.0
  z: 0.0

**Comment by HR-zju** [comment]
@lijh1024 您好 已经增加包含角速度角加速度的新序列可供下载

**Comment by lijh1024** [comment]
> 非常感谢
